// Code generated by toongen. DO NOT EDIT.

package example

import (
	"strconv"
)

// MarshalTOON implements toon.Marshaler
func (s User) MarshalTOON() ([]byte, error) {
	// Pre-allocate buffer (estimate: header + fields)
	buf := make([]byte, 0, 256)
	
	// Header: name{field1,field2}:
	buf = append(buf, "user{"...)
	buf = append(buf, "id"...),
	buf = append(buf, "name"...),
	buf = append(buf, "age"...)
	buf = append(buf, "}:"...)
	
	// Values
	
buf = strconv.AppendInt(buf, int64(s.ID), 10)

	buf = append(buf, ',')
	
buf = append(buf, s.Name...)

	buf = append(buf, ',')
	
buf = strconv.AppendInt(buf, int64(s.Age), 10)

	
	return buf, nil
}

// UnmarshalTOON implements toon.Unmarshaler
func (s *User) UnmarshalTOON(data []byte) error {
	// Skip header: find colon
	colonIdx := -1
	for i, b := range data {
		if b == ':' {
			colonIdx = i
			break
		}
	}
	if colonIdx == -1 {
		return strconv.ErrSyntax
	}
	
	// Parse values after colon
	data = data[colonIdx+1:]
	// Parse ID (int)
	
commaIdx := -1
for i, b := range data {
	if b == ',' {
		commaIdx = i
		break
	}
}
if commaIdx == -1 {
	commaIdx = len(data)
}
n, _ := strconv.ParseInt(string(data[:commaIdx]), 10, 64)
s.ID = int(n)
data = data[commaIdx+1:]

	// Parse Name (string)
	
commaIdx := -1
for i, b := range data {
	if b == ',' {
		commaIdx = i
		break
	}
}
if commaIdx == -1 {
	commaIdx = len(data)
}
s.Name = string(data[:commaIdx])
data = data[commaIdx+1:]

	// Parse Age (int)
	
commaIdx := -1
for i, b := range data {
	if b == ',' {
		commaIdx = i
		break
	}
}
if commaIdx == -1 {
	commaIdx = len(data)
}
n, _ := strconv.ParseInt(string(data[:commaIdx]), 10, 64)
s.Age = int(n)
data = data[commaIdx+1:]

	
	return nil
}
// Code generated by toongen. DO NOT EDIT.

package example

import (
	"strconv"
)

// MarshalTOON implements toon.Marshaler
func (s Product) MarshalTOON() ([]byte, error) {
	// Pre-allocate buffer (estimate: header + fields)
	buf := make([]byte, 0, 256)
	
	// Header: name{field1,field2}:
	buf = append(buf, "product{"...)
	buf = append(buf, "sku"...),
	buf = append(buf, "price"...)
	buf = append(buf, "}:"...)
	
	// Values
	
buf = append(buf, s.SKU...)

	buf = append(buf, ',')
	
buf = strconv.AppendFloat(buf, s.Price, 'f', -1, 64)

	
	return buf, nil
}

// UnmarshalTOON implements toon.Unmarshaler
func (s *Product) UnmarshalTOON(data []byte) error {
	// Skip header: find colon
	colonIdx := -1
	for i, b := range data {
		if b == ':' {
			colonIdx = i
			break
		}
	}
	if colonIdx == -1 {
		return strconv.ErrSyntax
	}
	
	// Parse values after colon
	data = data[colonIdx+1:]
	// Parse SKU (string)
	
commaIdx := -1
for i, b := range data {
	if b == ',' {
		commaIdx = i
		break
	}
}
if commaIdx == -1 {
	commaIdx = len(data)
}
s.SKU = string(data[:commaIdx])
data = data[commaIdx+1:]

	
	return nil
}
