// Code generated by toongen. DO NOT EDIT.

package example

import (
	"hash/fnv"
	"strconv"
)

func estimateIntTokens(n int) int {
	if n == 0 { return 1 }
	count := 0
	if n < 0 { count++; n = -n }
	for n > 0 { count++; n /= 10 }
	return count
}

// toonSchemaHashUser is the pre-computed header hash for fast validation
const toonSchemaHashUser = 6784022818517490669

// toonHeaderUser is the expected header string
var toonHeaderUser = "user{" + "id,name,age}:" + ""

// ToonTokenCount returns estimated token count for LLM context
func (s User) ToonTokenCount() int {
	count := 3 + 4 // separators + header overhead
	count += estimateIntTokens(s.ID)
	count += len(s.Name) / 4
	count += estimateIntTokens(s.Age)
	return count
}

func (s User) MarshalTOON() ([]byte, error) {
	buf := make([]byte, 0, 256)
	buf = append(buf, toonHeaderUser...)
	
buf = strconv.AppendInt(buf, int64(s.ID), 10)

	buf = append(buf, ',')
	
buf = append(buf, s.Name...)

	buf = append(buf, ',')
	
buf = strconv.AppendInt(buf, int64(s.Age), 10)

	return buf, nil
}

func (s *User) UnmarshalTOON(data []byte) error {
	var commaIdx int
	colonIdx := -1
	for i, b := range data {
		if b == ':' {
			colonIdx = i
			break
		}
	}
	if colonIdx == -1 {
		return strconv.ErrSyntax
	}
	if colonIdx+1 != len(toonHeaderUser) {
		return strconv.ErrSyntax
	}
	h := fnv.New64a()
	h.Write(data[:colonIdx])
	if h.Sum64() != toonSchemaHashUser {
		return strconv.ErrSyntax
	}
	data = data[colonIdx+1:]
	
commaIdx = -1
for i, b := range data {
	if b == ',' {
		commaIdx = i
		break
	}
}
if commaIdx == -1 {
	commaIdx = len(data)
}
IDVal, _ := strconv.ParseInt(string(data[:commaIdx]), 10, 64)
s.ID = int(IDVal)
if commaIdx < len(data) {
	data = data[commaIdx+1:]
}

	
commaIdx = -1
for i, b := range data {
	if b == ',' {
		commaIdx = i
		break
	}
}
if commaIdx == -1 {
	commaIdx = len(data)
}
s.Name = string(data[:commaIdx])
if commaIdx < len(data) {
	data = data[commaIdx+1:]
}

	
commaIdx = -1
for i, b := range data {
	if b == ',' {
		commaIdx = i
		break
	}
}
if commaIdx == -1 {
	commaIdx = len(data)
}
AgeVal, _ := strconv.ParseInt(string(data[:commaIdx]), 10, 64)
s.Age = int(AgeVal)
if commaIdx < len(data) {
	data = data[commaIdx+1:]
}

	return nil
}

// toonSchemaHashProduct is the pre-computed header hash for fast validation
const toonSchemaHashProduct = 1151880722861511562

// toonHeaderProduct is the expected header string
var toonHeaderProduct = "product{" + "sku,price}:" + ""

// ToonTokenCount returns estimated token count for LLM context
func (s Product) ToonTokenCount() int {
	count := 2 + 4 // separators + header overhead
	count += len(s.SKU) / 4
	return count
}

func (s Product) MarshalTOON() ([]byte, error) {
	buf := make([]byte, 0, 256)
	buf = append(buf, toonHeaderProduct...)
	
buf = append(buf, s.SKU...)

	buf = append(buf, ',')
	
buf = strconv.AppendFloat(buf, s.Price, 'f', -1, 64)

	return buf, nil
}

func (s *Product) UnmarshalTOON(data []byte) error {
	var commaIdx int
	colonIdx := -1
	for i, b := range data {
		if b == ':' {
			colonIdx = i
			break
		}
	}
	if colonIdx == -1 {
		return strconv.ErrSyntax
	}
	if colonIdx+1 != len(toonHeaderProduct) {
		return strconv.ErrSyntax
	}
	h := fnv.New64a()
	h.Write(data[:colonIdx])
	if h.Sum64() != toonSchemaHashProduct {
		return strconv.ErrSyntax
	}
	data = data[colonIdx+1:]
	
commaIdx = -1
for i, b := range data {
	if b == ',' {
		commaIdx = i
		break
	}
}
if commaIdx == -1 {
	commaIdx = len(data)
}
s.SKU = string(data[:commaIdx])
if commaIdx < len(data) {
	data = data[commaIdx+1:]
}

	
commaIdx = -1
for i, b := range data {
	if b == ',' {
		commaIdx = i
		break
	}
}
if commaIdx == -1 {
	commaIdx = len(data)
}
PriceVal, _ := strconv.ParseFloat(string(data[:commaIdx]), 64)
s.Price = PriceVal
if commaIdx < len(data) {
	data = data[commaIdx+1:]
}

	return nil
}
