package toon

import (
	"testing"
	"time"
)

func TestDecoderNext(t *testing.T) {
	d := newDecoder([]byte("abc"))
	
	b, ok := d.next()
	if !ok || b != 'a' {
		t.Errorf("expected 'a', got %c", b)
	}
	
	b, ok = d.peek()
	if !ok || b != 'b' {
		t.Errorf("expected 'b' peek, got %c", b)
	}
	
	// pos should still be 1 after peek
	if d.pos != 1 {
		t.Errorf("expected pos=1 after peek, got %d", d.pos)
	}
}

func TestParseHeader(t *testing.T) {
	tests := []struct {
		name    string
		input   string
		want    *header
		wantErr bool
	}{
		{
			name:  "simple name",
			input: "users:",
			want:  &header{name: []byte("users"), size: -1},
		},
		{
			name:  "with size",
			input: "users[10]:",
			want:  &header{name: []byte("users"), size: 10},
		},
		{
			name:  "with fields",
			input: "users{id,name,age}:",
			want:  &header{name: []byte("users"), size: -1, fields: [][]byte{[]byte("id"), []byte("name"), []byte("age")}},
		},
		{
			name:  "full header",
			input: "users[2]{id,name}:",
			want:  &header{name: []byte("users"), size: 2, fields: [][]byte{[]byte("id"), []byte("name")}},
		},
		{
			name:    "missing colon",
			input:   "users",
			wantErr: true,
		},
		{
			name:    "invalid size",
			input:   "users[abc]:",
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			d := newDecoder([]byte(tt.input))
			got, err := d.parseHeader()
			
			if tt.wantErr {
				if err == nil {
					t.Error("expected error, got nil")
				}
				return
			}
			
			if err != nil {
				t.Errorf("unexpected error: %v", err)
				return
			}
			
			if !bytesEqual(got.name, tt.want.name) {
				t.Errorf("name: got %q, want %q", got.name, tt.want.name)
			}
			if got.size != tt.want.size {
				t.Errorf("size: got %d, want %d", got.size, tt.want.size)
			}
			if len(got.fields) != len(tt.want.fields) {
				t.Errorf("fields len: got %d, want %d", len(got.fields), len(tt.want.fields))
			}
			for i := range got.fields {
				if !bytesEqual(got.fields[i], tt.want.fields[i]) {
					t.Errorf("field[%d]: got %q, want %q", i, got.fields[i], tt.want.fields[i])
				}
			}
		})
	}
}

func TestUnmarshalStruct(t *testing.T) {
	type User struct {
		ID   int
		Name string
	}

	// lowercase field names (as generated by cache.go)
	data := []byte("user{id,name}:42,John")
	
	var u User
	err := Unmarshal(data, &u)
	if err != nil {
		t.Fatalf("unmarshal error: %v", err)
	}
	
	if u.ID != 42 {
		t.Errorf("ID: expected 42, got %d", u.ID)
	}
	if u.Name != "John" {
		t.Errorf("Name: expected John, got %s", u.Name)
	}
}

func TestUnmarshalSlice(t *testing.T) {
	type User struct {
		ID   int
		Name string
	}

	// lowercase field names (as generated by cache.go)
	data := []byte("users[2]{id,name}:42,John\n43,Jane")
	
	var users []User
	err := Unmarshal(data, &users)
	if err != nil {
		t.Fatalf("unmarshal error: %v", err)
	}
	
	if len(users) != 2 {
		t.Fatalf("expected 2 users, got %d", len(users))
	}
	
	if users[0].ID != 42 || users[0].Name != "John" {
		t.Errorf("user[0]: expected {42 John}, got {%d %s}", users[0].ID, users[0].Name)
	}
	
	if users[1].ID != 43 || users[1].Name != "Jane" {
		t.Errorf("user[1]: expected {43 Jane}, got {%d %s}", users[1].ID, users[1].Name)
	}
}

func TestUnmarshalInvalidTarget(t *testing.T) {
	err := Unmarshal([]byte("test:"), "not a pointer")
	if err != ErrInvalidTarget {
		t.Errorf("expected ErrInvalidTarget, got %v", err)
	}
	
	var i int
	err = Unmarshal([]byte("test:"), &i)
	if err != ErrInvalidTarget {
		t.Errorf("expected ErrInvalidTarget for non-struct/slice, got %v", err)
	}
}

func TestUnmarshalRootListNonUniformObjectsDoesNotHang(t *testing.T) {
	data := []byte("[2]:\n  - id: 1\n  - id: 2\n    name: Ada")
	var out []map[string]interface{}

	done := make(chan error, 1)
	go func() {
		done <- Unmarshal(data, &out)
	}()

	select {
	case err := <-done:
		if err != nil {
			t.Fatalf("unexpected unmarshal error: %v", err)
		}
	case <-time.After(1 * time.Second):
		t.Fatal("unmarshal timed out; possible parser loop regression")
	}

	if len(out) != 2 {
		t.Fatalf("expected 2 items, got %d", len(out))
	}
	if id, ok := out[0]["id"].(int); !ok || id != 1 {
		t.Fatalf("expected first item id=1, got %#v", out[0]["id"])
	}
	if id, ok := out[1]["id"].(int); !ok || id != 2 {
		t.Fatalf("expected second item id=2, got %#v", out[1]["id"])
	}
	if name, ok := out[1]["name"].(string); !ok || name != "Ada" {
		t.Fatalf("expected second item name=Ada, got %#v", out[1]["name"])
	}
}

func FuzzUnmarshalNoPanic(f *testing.F) {
	seeds := [][]byte{
		[]byte(""),
		[]byte("user{id,name}:1,Ada"),
		[]byte("[2]:\n  - id: 1\n  - id: 2\n    name: Ada"),
		[]byte("[5]: x,y,\"true\",true,10"),
		[]byte("items[2]:\n  - [2]: 1,2\n  - [0]:"),
	}
	for _, s := range seeds {
		f.Add(s)
	}

	f.Fuzz(func(t *testing.T, data []byte) {
		var out struct{}
		defer func() {
			if r := recover(); r != nil {
				t.Fatalf("unmarshal panicked: %v", r)
			}
		}()
		_ = Unmarshal(data, &out)
	})
}
