package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// StructInfo holds info about a struct to generate
type StructInfo struct {
	Package string
	Name    string
	Fields  []FieldInfo
}

// FieldInfo holds info about a struct field
type FieldInfo struct {
	Name     string
	Type     string
	JSONName string
	ToonName string
}

const toonTmpl = `// Code generated by toongen. DO NOT EDIT.

package {{.Package}}

import (
	"strconv"
)

// MarshalTOON implements toon.Marshaler
func (s {{.Name}}) MarshalTOON() ([]byte, error) {
	// Pre-allocate buffer (estimate: header + fields)
	buf := make([]byte, 0, 256)
	
	// Header: name{field1,field2}:
	buf = append(buf, "{{.Name | lower}}{"...)
	{{- range $i, $f := .Fields}}
	{{- if $i}},{{end}}
	buf = append(buf, "{{$f.ToonName}}"...)
	{{- end}}
	buf = append(buf, "}:"...)
	
	// Values
	{{- range $i, $f := .Fields}}
	{{- if $i}}
	buf = append(buf, ',')
	{{- end}}
	{{template "marshalField" $f}}
	{{- end}}
	
	return buf, nil
}

// UnmarshalTOON implements toon.Unmarshaler
func (s *{{.Name}}) UnmarshalTOON(data []byte) error {
	// Skip header: find colon
	colonIdx := -1
	for i, b := range data {
		if b == ':' {
			colonIdx = i
			break
		}
	}
	if colonIdx == -1 {
		return strconv.ErrSyntax
	}
	
	// Parse values after colon
	data = data[colonIdx+1:]
	{{- range $i, $f := .Fields}}
	{{- if eq $f.Type "int"}}
	// Parse {{$f.Name}} (int)
	{{template "parseInt" $f}}
	{{- else if eq $f.Type "string"}}
	// Parse {{$f.Name}} (string)
	{{template "parseString" $f}}
	{{- else if eq $f.Type "bool"}}
	// Parse {{$f.Name}} (bool)
	{{template "parseBool" $f}}
	{{- end}}
	{{- end }}
	
	return nil
}
`

const marshalFieldTmpl = `{{define "marshalField"}}
{{- if eq .Type "int"}}
buf = strconv.AppendInt(buf, int64(s.{{.Name}}), 10)
{{- else if eq .Type "string"}}
buf = append(buf, s.{{.Name}}...)
{{- else if eq .Type "bool"}}
if s.{{.Name}} {
	buf = append(buf, '+')
} else {
	buf = append(buf, '-')
}
{{- else if eq .Type "float64"}}
buf = strconv.AppendFloat(buf, s.{{.Name}}, 'f', -1, 64)
{{- end}}
{{end}}`

const parseIntTmpl = `{{define "parseInt"}}
commaIdx := -1
for i, b := range data {
	if b == ',' {
		commaIdx = i
		break
	}
}
if commaIdx == -1 {
	commaIdx = len(data)
}
n, _ := strconv.ParseInt(string(data[:commaIdx]), 10, 64)
s.{{.Name}} = int(n)
data = data[commaIdx+1:]
{{end}}`

const parseStringTmpl = `{{define "parseString"}}
commaIdx := -1
for i, b := range data {
	if b == ',' {
		commaIdx = i
		break
	}
}
if commaIdx == -1 {
	commaIdx = len(data)
}
s.{{.Name}} = string(data[:commaIdx])
data = data[commaIdx+1:]
{{end}}`

const parseBoolTmpl = `{{define "parseBool"}}
if len(data) > 0 && (data[0] == '+' || data[0] == '1' || data[0] == 't' || data[0] == 'T') {
	s.{{.Name}} = true
} else {
	s.{{.Name}} = false
}
// Skip value and comma
commaIdx := -1
for i, b := range data {
	if b == ',' {
		commaIdx = i
		break
	}
}
if commaIdx == -1 {
	commaIdx = len(data) - 1
}
data = data[commaIdx+1:]
{{end}}`

func main() {
	var (
		input  = flag.String("i", ".", "input directory")
		output = flag.String("o", "", "output file (default: <input>/_toon.go)")
	)
	flag.Parse()

	if *output == "" {
		*output = filepath.Join(*input, "_toon.go")
	}

	structs, pkgName, err := parseStructs(*input)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing: %v\n", err)
		os.Exit(1)
	}

	if len(structs) == 0 {
		fmt.Println("No structs with //toon:generate found")
		return
	}

	if err := generate(*output, pkgName, structs); err != nil {
		fmt.Fprintf(os.Stderr, "Error generating: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s with %d structs\n", *output, len(structs))
}

func parseStructs(dir string) ([]StructInfo, string, error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, nil, parser.ParseComments)
	if err != nil {
		return nil, "", err
	}

	var structs []StructInfo
	var pkgName string

	for name, pkg := range pkgs {
		if strings.HasSuffix(name, "_test") {
			continue
		}
		pkgName = name

		for filename, file := range pkg.Files {
			if strings.HasSuffix(filename, "_toon.go") || strings.HasSuffix(filename, ".gen.go") {
				continue
			}

			ast.Inspect(file, func(n ast.Node) bool {
				genDecl, ok := n.(*ast.GenDecl)
				if !ok || genDecl.Tok != token.TYPE {
					return true
				}

				// Check for //toon:generate comment
				if !hasToonGenerate(genDecl.Doc) {
					return true
				}

				for _, spec := range genDecl.Specs {
					typeSpec, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}

					structType, ok := typeSpec.Type.(*ast.StructType)
					if !ok {
						continue
					}

					info := StructInfo{
						Name:   typeSpec.Name.Name,
						Fields: extractFields(structType),
					}
					structs = append(structs, info)
				}
				return true
			})
		}
	}

	return structs, pkgName, nil
}

func hasToonGenerate(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}
	for _, comment := range doc.List {
		if strings.Contains(comment.Text, "toon:generate") {
			return true
		}
	}
	return false
}

func extractFields(st *ast.StructType) []FieldInfo {
	var fields []FieldInfo
	for _, field := range st.Fields.List {
		if len(field.Names) == 0 {
			continue
		}

		name := field.Names[0].Name
		if !ast.IsExported(name) {
			continue
		}

		fieldType := exprToString(field.Type)
		toonName := name
		if tag := field.Tag; tag != nil {
			tagValue := strings.Trim(tag.Value, "`")
			if val := extractTag(tagValue, "toon"); val != "" && val != "-" {
				toonName = val
			}
		}

		fields = append(fields, FieldInfo{
			Name:     name,
			Type:     fieldType,
			ToonName: strings.ToLower(toonName),
		})
	}
	return fields
}

func exprToString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return "*" + exprToString(t.X)
	case *ast.ArrayType:
		return "[]" + exprToString(t.Elt)
	case *ast.SelectorExpr:
		return exprToString(t.X) + "." + t.Sel.Name
	default:
		return fmt.Sprintf("%T", expr)
	}
}

func extractTag(tag, key string) string {
	// Simple tag parser: `key:"value"`
	prefix := key + ":\""
	start := strings.Index(tag, prefix)
	if start == -1 {
		return ""
	}
	start += len(prefix)
	end := strings.Index(tag[start:], "\"")
	if end == -1 {
		return ""
	}
	return tag[start : start+end]
}

func generate(filename, pkgName string, structs []StructInfo) error {
	funcs := template.FuncMap{
		"lower": strings.ToLower,
	}

	tmpl, err := template.New("toon").Funcs(funcs).Parse(toonTmpl)
	if err != nil {
		return err
	}

	// Parse sub-templates
	tmpl, err = tmpl.Parse(marshalFieldTmpl)
	if err != nil {
		return err
	}
	tmpl, err = tmpl.Parse(parseIntTmpl)
	if err != nil {
		return err
	}
	tmpl, err = tmpl.Parse(parseStringTmpl)
	if err != nil {
		return err
	}
	tmpl, err = tmpl.Parse(parseBoolTmpl)
	if err != nil {
		return err
	}

	file, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer file.Close()

	for _, s := range structs {
		s.Package = pkgName
		if err := tmpl.Execute(file, s); err != nil {
			return err
		}
	}

	return nil
}
